version: '3.8'

services:
  streamlit_app:
    build: .
    container_name: streamlit_container
    ports:
      - "8501:8501"  # Maps host port 8501 to container port 8501
    volumes:
      - ./:/app  # Mounts the app directory for code changes